# Generated by Django 4.2 on 2023-10-06 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiftickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
