# Generated by Django 4.2 on 2023-10-06 04:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swiftickets', '0002_user_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isEvent',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Show', 'Show'), ('Festival', 'Festival')], max_length=14)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('state', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], default='Open', max_length=14)),
                ('uf', models.CharField(blank=True, choices=[('Acre', 'Acre'), ('Alagoas', 'Alagoas'), ('Amapá', 'Amapá'), ('Amazonas', 'Amazonas'), ('Bahia', 'Bahia'), ('Ceará', 'Ceará'), ('DistritoFederal', 'Distritofederal'), ('EspíritoSanto', 'Espíritosanto'), ('Goiás', 'Goiás'), ('Maranhão', 'Maranhão'), ('MatoGrosso', 'Matogrosso'), ('MatoGrossodoSul', 'Matogrossodosul'), ('MinasGerais', 'Minasgerais'), ('Pará', 'Pará'), ('Paraíba', 'Paraíba'), ('Paraná', 'Paraná'), ('Pernambuco', 'Pernambuco'), ('Piauí', 'Piauí'), ('RiodeJaneiro', 'Riodejaneiro'), ('RioGrandedoNorte', 'Riograndedonorte'), ('RioGrandedoSul', 'Riograndedosul'), ('Rondônia', 'Rondônia'), ('Roraima', 'Roraima'), ('SantaCatarina', 'Santacatarina'), ('SãoPaulo', 'Sãopaulo'), ('Sergipe', 'Sergipe'), ('Tocantins', 'Tocantins')], max_length=16, null=True)),
                ('registrant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
            },
        ),
    ]
