# Generated by Django 4.2 on 2023-10-07 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('swiftickets', '0004_ticket_price_purchase'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'verbose_name': 'Purchase', 'verbose_name_plural': 'Purchases'},
        ),
        migrations.RenameField(
            model_name='user',
            old_name='isEvent',
            new_name='is_owner',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='description',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='name',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='registrant',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='state',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='type',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='uf',
        ),
        migrations.AddField(
            model_name='ticket',
            name='quantity_available',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sale_end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sale_start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Vip', 'Vip')], default='', max_length=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='cpf',
            field=models.CharField(blank=True, default='', max_length=14),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Show', 'Show'), ('Festival', 'Festival')], max_length=14)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, default='', max_length=255)),
                ('state', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], default='Open', max_length=14)),
                ('uf', models.CharField(blank=True, choices=[('Acre', 'Acre'), ('Alagoas', 'Alagoas'), ('Amapá', 'Amapá'), ('Amazonas', 'Amazonas'), ('Bahia', 'Bahia'), ('Ceará', 'Ceará'), ('DistritoFederal', 'Distritofederal'), ('EspíritoSanto', 'Espíritosanto'), ('Goiás', 'Goiás'), ('Maranhão', 'Maranhão'), ('MatoGrosso', 'Matogrosso'), ('MatoGrossodoSul', 'Matogrossodosul'), ('MinasGerais', 'Minasgerais'), ('Pará', 'Pará'), ('Paraíba', 'Paraíba'), ('Paraná', 'Paraná'), ('Pernambuco', 'Pernambuco'), ('Piauí', 'Piauí'), ('RiodeJaneiro', 'Riodejaneiro'), ('RioGrandedoNorte', 'Riograndedonorte'), ('RioGrandedoSul', 'Riograndedosul'), ('Rondônia', 'Rondônia'), ('Roraima', 'Roraima'), ('SantaCatarina', 'Santacatarina'), ('SãoPaulo', 'Sãopaulo'), ('Sergipe', 'Sergipe'), ('Tocantins', 'Tocantins')], max_length=16, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('open_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('close_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('registrant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='event',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='swiftickets.event'),
            preserve_default=False,
        ),
    ]
