# Generated by Django 4.2 on 2023-10-09 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiftickets', '0005_alter_purchase_options_rename_isevent_user_is_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='num_edit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
